# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chaney
email: justfy.hi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Coder in Beijing , Java developer , Google fans 
baseurl: "https://bjchaney.com" # the subpath of your site, e.g. /blog
url: "https://BJChaney.github.io" # the base hostname & protocol for your site
github_username:  BJChaney
motto: "行胜于言,持之以恒。"
# Build settings
markdown: kramdown
