# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BJChaney's blog
email: justfy.hi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Coder in Beijing , Java developer , Google fans 
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.bjchany.com" # the base hostname & protocol for your site
twitter_username: fareez_ahamed
github_username:  BJChaney

# Build settings
markdown: kramdown
